name: RiggerConnect
options:
  bundleIdPrefix: com.chasewhiterabbit
  createIntermediateGroups: true
  developmentLanguage: en
  minimumXcodeGenVersion: 2.38.0

packages:
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk.git
    from: 10.20.0
  Stripe:
    url: https://github.com/stripe/stripe-ios.git
    from: 23.24.0
  SwiftSoup:
    url: https://github.com/scinfu/SwiftSoup.git
    from: 2.6.1
  Alamofire:
    url: https://github.com/Alamofire/Alamofire.git
    from: 5.8.0
  SDWebImage:
    url: https://github.com/SDWebImage/SDWebImage.git
    from: 5.18.0
  KeychainAccess:
    url: https://github.com/kishikawakatsumi/KeychainAccess.git
    from: 4.2.2
  SwiftCollections:
    url: https://github.com/apple/swift-collections.git
    from: 1.0.0
  SwiftCrypto:
    url: https://github.com/apple/swift-crypto.git
    from: 3.0.0
  SwiftLog:
    url: https://github.com/apple/swift-log.git
    from: 1.5.0

targets:
  RiggerShared:
    type: framework
    platform: iOS
    deploymentTarget: 15.0
    sources:
      - path: Sources/RiggerShared
    resources:
      - Sources/RiggerShared/Resources
    dependencies:
      - package: Firebase
        product: FirebaseAuth
      - package: Firebase
        product: FirebaseFirestore  
      - package: Firebase
        product: FirebaseAnalytics
      - package: Firebase
        product: FirebaseMessaging
      - package: Alamofire
        product: Alamofire
      - package: SDWebImage
        product: SDWebImage
      - package: KeychainAccess
        product: KeychainAccess
      - package: SwiftCollections
        product: Collections
      - package: SwiftCrypto
        product: Crypto
      - package: SwiftLog
        product: Logging
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.chasewhiterabbit.riggershared
      MARKETING_VERSION: 1.0.0
      CURRENT_PROJECT_VERSION: 1
      IPHONEOS_DEPLOYMENT_TARGET: 15.0
      SWIFT_VERSION: 5.9
      GENERATE_INFOPLIST_FILE: YES
      CODE_SIGN_STYLE: Automatic
      
  RiggerConnect:
    type: application
    platform: iOS
    deploymentTarget: 15.0
    sources:
      - path: Sources/RiggerConnect
    resources:
      - Sources/RiggerConnect/Resources
    dependencies:
      - target: RiggerShared
      - package: Firebase
        product: FirebaseAuth
      - package: Firebase
        product: FirebaseFirestore  
      - package: Firebase
        product: FirebaseAnalytics
      - package: Firebase
        product: FirebaseMessaging
      - package: Stripe
        product: StripePaymentsUI
      - package: Alamofire
        product: Alamofire
      - package: SDWebImage
        product: SDWebImage
      - package: KeychainAccess
        product: KeychainAccess
      - package: SwiftCollections
        product: Collections
      - package: SwiftCrypto
        product: Crypto
      - package: SwiftLog
        product: Logging
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.chasewhiterabbit.riggerconnect
      MARKETING_VERSION: 1.0.0
      CURRENT_PROJECT_VERSION: 1
      IPHONEOS_DEPLOYMENT_TARGET: 15.0
      SWIFT_VERSION: 5.9
      DEVELOPMENT_TEAM: # Add your team ID here
      GENERATE_INFOPLIST_FILE: YES
      CODE_SIGN_STYLE: Automatic
      
  RiggerHub:
    type: application
    platform: iOS
    deploymentTarget: 15.0
    sources:
      - path: Sources/RiggerHub
    resources:
      - Sources/RiggerHub/Resources
    dependencies:
      - target: RiggerShared
      - package: Firebase
        product: FirebaseAuth
      - package: Firebase
        product: FirebaseFirestore
      - package: Firebase
        product: FirebaseAnalytics
      - package: Firebase
        product: FirebaseMessaging
      - package: Alamofire
        product: Alamofire
      - package: SDWebImage
        product: SDWebImage
      - package: KeychainAccess
        product: KeychainAccess
      - package: SwiftCollections
        product: Collections
      - package: SwiftCrypto
        product: Crypto
      - package: SwiftLog
        product: Logging
      - package: SwiftSoup
        product: SwiftSoup
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.chasewhiterabbit.riggerhub
      MARKETING_VERSION: 1.0.0
      CURRENT_PROJECT_VERSION: 1
      IPHONEOS_DEPLOYMENT_TARGET: 15.0
      SWIFT_VERSION: 5.9
      DEVELOPMENT_TEAM: # Add your team ID here
      GENERATE_INFOPLIST_FILE: YES
      CODE_SIGN_STYLE: Automatic

schemes:
  RiggerShared:
    build:
      targets:
        RiggerShared: all
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release

  RiggerConnect:
    build:
      targets:
        RiggerConnect: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release

  RiggerHub:
    build:
      targets:
        RiggerHub: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
